# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e1e325165d9914296af73c64bc727faf87e52d0d69e2692ccd0471b918d31ad084a43bf85120e5a2658ada209ef5f4c23671500c81aadab6ae5f16c96d368d

test:
  secret_key_base: dabc5560489b9868ee0c69bd0bb9fe1ed6b95685a3c18dc9670396856322eba33f18fb5036bee15989c2672318f0107a306fde818f672617fff49aa87431df7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
